server:
  port: 5050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: stok
          uri: http://localhost:5050/stok/
          predicates:
            - Path= /stok/**
            #==========================
        - id: auth
          uri: http://localhost:7070/auth/
          predicates:
            - Path= /auth/**
            #==========================